### ISSUE TITLE
Disable Nagle's algorithm for TCP

### ISSUE THREAD

**Issue by TrueBrain** [pgroen/modbus-cpp#3]
By default the kernel has `TCP_NODELAY` disabled on any socket. This enables Nagle's alrogithm. But for ModBus, that most likely hurts more than it solves, and can (significantly) increase latency.

Can I suggest to set `TCP_NODELAY` to avoid that problem? That way, when you do a `write`, the packet is written without delay on the network stack.

Lower latency == more profit, or something :)

**Comment by pgroen** [comment]
Done. Is added into the branch "encompassing object"
